#set_property CLOCK_DEDICATED_ROUTE FALSE [ get_nets {clk} ]
#set_property CLOCK_DEDICATED_ROUTE FALSE [ get_nets {start_pulse} ]

set_property PACKAGE_PIN P4 [get_ports {clk}]
set_property PACKAGE_PIN P3 [get_ports {start_pulse}]
set_property PACKAGE_PIN T8 [get_ports {output_pulse}]
set_property PACKAGE_PIN R7 [get_ports control_register[ 0 ] ]
set_property PACKAGE_PIN R6 [get_ports control_register[ 1 ] ]
set_property PACKAGE_PIN R5 [get_ports control_register[ 2 ] ]
set_property PACKAGE_PIN V7 [get_ports control_register[ 3 ] ]
set_property PACKAGE_PIN V6 [get_ports control_register[ 4 ] ]
set_property PACKAGE_PIN V5 [get_ports control_register[ 5 ] ]

set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {start_pulse}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_pulse}]
set_property IOSTANDARD LVCMOS33 [get_ports control_register[ 0 ] ]
set_property IOSTANDARD LVCMOS33 [get_ports control_register[ 1 ] ]
set_property IOSTANDARD LVCMOS33 [get_ports control_register[ 2 ] ]
set_property IOSTANDARD LVCMOS33 [get_ports control_register[ 3 ] ]
set_property IOSTANDARD LVCMOS33 [get_ports control_register[ 4 ] ]
set_property IOSTANDARD LVCMOS33 [get_ports control_register[ 5 ] ]
